-- Grant Privilages to HMS_OPERATOR 

-- Grant privileges on ALL 9 tables
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.ADMIN TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.BROKER TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.OWNER TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.PROPERTY TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.BROKER_PROPERTY TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.STUDENT TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.WISHLIST TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.BOOKING TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.TOUR TO HMS_OPERATOR;