show user;

SET SERVEROUTPUT ON;

--Drop if already exists 
-- DROP USER HMS_ADMIN CASCADE;
BEGIN
    EXECUTE IMMEDIATE 'DROP USER HMS_ADMIN CASCADE';
    DBMS_OUTPUT.PUT_LINE('User HMS_ADMIN dropped successfully.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1918 THEN
            DBMS_OUTPUT.PUT_LINE('User HMS_ADMIN does not exist.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP USER HMS_OPERATOR CASCADE';
    DBMS_OUTPUT.PUT_LINE('User HMS_OPERATOR dropped successfully.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1918 THEN
            DBMS_OUTPUT.PUT_LINE('User HMS_OPERATOR does not exist.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
        END IF;
END;
/

--Create HMS_ADMIN
CREATE USER HMS_ADMIN IDENTIFIED BY AdminNeuBoston2025#;

--Grant privileges for schema creation
GRANT CREATE SESSION TO HMS_ADMIN;
GRANT CREATE TABLE TO HMS_ADMIN;
GRANT CREATE VIEW TO HMS_ADMIN;
GRANT CREATE SEQUENCE TO HMS_ADMIN;
--GRANT CREATE TRIGGER TO HMS_ADMIN;
--GRANT CREATE SYNONYM TO HMS_ADMIN;
GRANT UNLIMITED TABLESPACE TO HMS_ADMIN;

ALTER USER HMS_ADMIN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--Create HMS_OPERATOR
CREATE USER HMS_OPERATOR IDENTIFIED BY Operator#2025;
GRANT CREATE SESSION TO HMS_OPERATOR;


--------------------------------------------------------------

