show user;


--Drop if already exists (optional)
DROP USER HMS_ADMIN CASCADE;
DROP USER HMSAdmin CASCADE;
DROP USER HMS_OPERATOR CASCADE;

--Create HMS_ADMIN
CREATE USER HMS_ADMIN IDENTIFIED BY AdminNeuBoston2025#;

--Grant privileges for schema creation
GRANT CREATE SESSION TO HMS_ADMIN;
GRANT CREATE TABLE TO HMS_ADMIN;
GRANT CREATE VIEW TO HMS_ADMIN;
GRANT CREATE SEQUENCE TO HMS_ADMIN;
GRANT CREATE TRIGGER TO HMS_ADMIN;
GRANT CREATE SYNONYM TO HMS_ADMIN;
GRANT UNLIMITED TABLESPACE TO HMS_ADMIN;

ALTER USER HMS_ADMIN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--Create HMS_OPERATOR
CREATE USER HMS_OPERATOR IDENTIFIED BY Operator#2025;

--Grant privileges
GRANT CREATE SESSION TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.ADMIN TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.BOOKING TO HMS_OPERATOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON HMS_ADMIN.TOUR TO HMS_OPERATOR;

