show user;


-- Drop if already exists (optional)
DROP USER PROJECT_ADMIN CASCADE;
DROP USER HMS_ADMIN CASCADE;
DROP USER HMSAdmin CASCADE;
DROP USER HMS_OPERATOR CASCADE;

-- Create PROJECT_ADMIN
CREATE USER PROJECT_ADMIN IDENTIFIED BY AdminNeuBoston2025#;

-- Grant privileges for schema creation
GRANT CREATE SESSION TO PROJECT_ADMIN;
GRANT CREATE TABLE TO PROJECT_ADMIN;
GRANT CREATE VIEW TO PROJECT_ADMIN;
GRANT CREATE SEQUENCE TO PROJECT_ADMIN;
GRANT CREATE TRIGGER TO PROJECT_ADMIN;
GRANT CREATE SYNONYM TO PROJECT_ADMIN;
GRANT UNLIMITED TABLESPACE TO PROJECT_ADMIN;

ALTER USER PROJECT_ADMIN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
